"""
=============================================================================
Lumina — Catalyst Data Store Provisioning Script
=============================================================================

Automates the creation of all 7 Data Store tables and their columns
using the Zoho Catalyst Management REST API.

Then optionally seeds the tables by uploading the synthetic CSV data
via the ZCQL bulk INSERT API.

Usage:
    python provision_datastore.py

Prerequisites:
    pip install requests

How to get your credentials:
    1. Go to https://api-console.zoho.com
    2. Click "Self Client"
    3. Scope: ZohoCatalyst.datastore.ALL,ZohoCatalyst.datastore.CREATE
    4. Duration: 10 minutes → Click "Create" → copy the token
    5. Your Project ID: open your project on catalyst.zoho.com and
       copy the number from the URL bar.

    Set these as environment variables OR edit the CONFIG block below:

    PowerShell:
        $env:CATALYST_PROJECT_ID   = "1234567890"
        $env:CATALYST_ACCESS_TOKEN = "your-token-here"
        python DataBase/provision_datastore.py

    Bash/Mac:
        export CATALYST_PROJECT_ID="1234567890"
        export CATALYST_ACCESS_TOKEN="your-token-here"
        python DataBase/provision_datastore.py
=============================================================================
"""

import os
import sys
import json
import time
import csv
import requests
from pathlib import Path

# ── CONFIG ────────────────────────────────────────────────────────────────────
# Edit these OR set as environment variables before running.

PROJECT_ID   = os.environ.get("CATALYST_PROJECT_ID", "")
ACCESS_TOKEN = os.environ.get("CATALYST_ACCESS_TOKEN", "")
ZOHO_DOMAIN  = os.environ.get("ZOHO_DOMAIN", "zoho.com")   # zoho.in / zoho.eu also valid

# Set to "false" to skip seeding data after table creation
SEED_DATA    = os.environ.get("SEED_DATA", "true").lower() == "true"

# Path to the synthetic CSV directory (generated by generate_synthetic_data.py)
CSV_DIR = Path(__file__).resolve().parent.parent / "data" / "synthetic"

# ── API Base URL ──────────────────────────────────────────────────────────────
BASE_URL = f"https://api.catalyst.{ZOHO_DOMAIN}/baas/v1/project/{PROJECT_ID}"


# ── Table Schema ──────────────────────────────────────────────────────────────
# Format: (column_name, catalyst_data_type, is_mandatory)
# Catalyst types: TEXT, NUMBER, DECIMAL, BOOLEAN, DATETIME, CLOB
# ROWID is auto-created — do NOT add it here.

SCHEMA = {
    "District": [
        ("Name",        "TEXT",    True),
        ("Code",        "TEXT",    True),
        ("Population",  "NUMBER",  True),
        ("Latitude",    "DECIMAL", False),
        ("Longitude",   "DECIMAL", False),
    ],
    "Police_Station": [
        ("District_ID",       "NUMBER",  True),
        ("Name",              "TEXT",    True),
        ("Jurisdiction_Area", "TEXT",    False),
        ("Latitude",          "DECIMAL", False),
        ("Longitude",         "DECIMAL", False),
    ],
    "FIR": [
        ("Station_ID",     "NUMBER",  True),
        ("FIR_Number",     "TEXT",    True),
        ("Date",           "TEXT",    True),
        ("Crime_Group",    "TEXT",    True),
        ("Crime_Subgroup", "TEXT",    False),
        ("Latitude",       "DECIMAL", True),
        ("Longitude",      "DECIMAL", True),
        ("Narrative",      "CLOB",    False),
        ("Status",         "TEXT",    True),
    ],
    "Accused": [
        ("Name",         "TEXT",   True),
        ("DOB",          "TEXT",   False),
        ("Gender",       "TEXT",   False),
        ("Occupation",   "TEXT",   False),
        ("Arrest_Count", "NUMBER", True),
    ],
    "Victim": [
        ("FIR_ID",               "NUMBER", True),
        ("Name",                 "TEXT",   True),
        ("DOB",                  "TEXT",   False),
        ("Gender",               "TEXT",   False),
        ("Socioeconomic_Status", "TEXT",   False),
    ],
    "Case_Accused": [
        ("FIR_ID",           "NUMBER", True),
        ("Accused_ID",       "NUMBER", True),
        ("Involvement_Type", "TEXT",   True),
    ],
    "Risk_Score": [
        ("District_ID",   "NUMBER",  True),
        ("Crime_Type",    "TEXT",    True),
        ("Score",         "DECIMAL", True),
        ("Forecast_Date", "TEXT",    True),
    ],
}

# Order matters — dependent tables come after their parents
TABLE_ORDER = [
    "District",
    "Police_Station",
    "FIR",
    "Accused",
    "Victim",
    "Case_Accused",
    "Risk_Score",
]

# CSV file name produced by the synthetic data generator for each table
CSV_MAP = {
    "District":      "districts.csv",
    "Police_Station": "police_stations.csv",
    "FIR":           "firs.csv",
    "Accused":       "accused.csv",
    "Victim":        "victims.csv",
    "Case_Accused":  "case_accused.csv",
    "Risk_Score":    "risk_scores.csv",
}


# ── API Helpers ───────────────────────────────────────────────────────────────

def _headers():
    return {
        "Authorization": f"Zoho-oauthtoken {ACCESS_TOKEN}",
        "Content-Type":  "application/json",
        "Accept":        "application/json",
    }


def api_get(path):
    r = requests.get(f"{BASE_URL}{path}", headers=_headers(), timeout=30)
    r.raise_for_status()
    return r.json()


def api_post(path, body):
    r = requests.post(
        f"{BASE_URL}{path}", headers=_headers(), json=body, timeout=30
    )
    r.raise_for_status()
    return r.json()


def log(msg, level="INFO"):
    icon = {"INFO": "✔", "WARN": "⚠", "ERROR": "✖", "STEP": "►"}.get(level, "•")
    print(f"  {icon}  {msg}")


# ── Validation ────────────────────────────────────────────────────────────────

def validate_config():
    errors = []
    if not PROJECT_ID:
        errors.append("CATALYST_PROJECT_ID is not set")
    if not ACCESS_TOKEN:
        errors.append("CATALYST_ACCESS_TOKEN is not set")
    if not errors:
        return

    print("\n[ERROR] Missing configuration:\n")
    for e in errors:
        print(f"  ✖  {e}")
    print("""
How to get your credentials:
  1. Go to: https://api-console.zoho.com
  2. Click "Self Client"
  3. Scope: ZohoCatalyst.datastore.ALL
  4. Duration: 10 minutes → "Create" → copy the token

  5. Your Project ID is in the URL when you open your Catalyst project:
     https://catalyst.zoho.com/b/.../<PROJECT_ID>/...

PowerShell:
  $env:CATALYST_PROJECT_ID   = "1234567890"
  $env:CATALYST_ACCESS_TOKEN = "paste-token-here"
  python DataBase/provision_datastore.py
""")
    sys.exit(1)


# ── Step 1: Create Tables & Columns ──────────────────────────────────────────

def get_existing_tables():
    """Return {table_name: table_id} for tables that already exist."""
    try:
        result = api_get("/table")
        return {t["table_name"]: t["table_id"] for t in result.get("data", [])}
    except Exception as e:
        log(f"Could not list existing tables: {e}", "WARN")
        return {}


def provision_tables():
    print("\n► STEP 1 — Creating Data Store tables\n")
    existing = get_existing_tables()

    for table_name in TABLE_ORDER:
        columns = SCHEMA[table_name]

        if table_name in existing:
            log(f"{table_name} — already exists, skipping", "WARN")
            continue

        try:
            print(f"\n  Creating: {table_name}")
            result = api_post("/table", {"table_name": table_name})
            table_id = result["data"]["table_id"]
            log(f"Table created (ID: {table_id})")

            for col_name, data_type, mandatory in columns:
                try:
                    api_post(f"/table/{table_id}/column", {
                        "column_name":   col_name,
                        "data_type":     data_type,
                        "is_mandatory":  mandatory,
                        "is_searchable": True,
                    })
                    flag = " [required]" if mandatory else ""
                    log(f"  + {col_name:<25} {data_type}{flag}")
                    time.sleep(0.2)
                except Exception as e:
                    log(f"  Column {col_name} failed: {e}", "ERROR")

        except Exception as e:
            log(f"Failed to create {table_name}: {e}", "ERROR")

        time.sleep(0.5)

    print("\n  ✔ All tables created.\n")


# ── Step 2: Seed Data from CSVs ───────────────────────────────────────────────

def _is_number(val):
    try:
        float(str(val))
        return True
    except (ValueError, TypeError):
        return False


def seed_table(table_name, csv_path):
    if not csv_path.exists():
        log(f"CSV not found: {csv_path.name} — skipping {table_name}", "WARN")
        return 0

    valid_cols = [col[0] for col in SCHEMA[table_name]]
    inserted = failed = 0

    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    log(f"Seeding {table_name}: {len(rows)} rows ...")

    for i, row in enumerate(rows):
        try:
            cols, vals = [], []
            for col in valid_cols:
                v = row.get(col, "")
                if v in (None, "", "nan", "NaN"):
                    continue
                cols.append(col)
                vals.append(str(v) if _is_number(v) else f"'{str(v).replace(chr(39), chr(39)+chr(39))}'")

            if not cols:
                continue

            query = f"INSERT INTO {table_name} ({', '.join(cols)}) VALUES ({', '.join(vals)})"
            api_post("/zcql", {"query": query})
            inserted += 1

            if (i + 1) % 200 == 0:
                log(f"  {i + 1}/{len(rows)} rows done...")

            time.sleep(0.05)   # ~20 inserts/sec

        except Exception as e:
            failed += 1
            if failed <= 3:
                log(f"  Row {i+1} failed: {e}", "WARN")

    log(f"  ✔ {table_name}: {inserted} inserted, {failed} failed")
    return inserted


def seed_all():
    print("\n► STEP 2 — Seeding tables with synthetic data\n")

    if not CSV_DIR.exists():
        log(
            f"CSV directory not found: {CSV_DIR}\n"
            "  Run the synthetic data generator first:\n"
            "  python data/generator/generate_synthetic_data.py",
            "WARN"
        )
        return

    total = 0
    for table_name in TABLE_ORDER:
        total += seed_table(table_name, CSV_DIR / CSV_MAP[table_name])
        time.sleep(1)

    print(f"\n  Total rows inserted: {total}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("\n" + "=" * 60)
    print("  Lumina — Catalyst Data Store Provisioner")
    print("=" * 60)

    validate_config()

    print(f"\n  Project ID : {PROJECT_ID}")
    print(f"  API Domain : api.catalyst.{ZOHO_DOMAIN}")
    print(f"  Seed data  : {SEED_DATA}")
    print(f"  CSV dir    : {CSV_DIR}")

    # Connectivity check
    try:
        log("\nTesting API connectivity ...")
        api_get("/table")
        log("Connected ✔")
    except Exception as e:
        log(f"Cannot reach Catalyst API: {e}", "ERROR")
        log("Verify your PROJECT_ID, ACCESS_TOKEN, and ZOHO_DOMAIN.", "ERROR")
        sys.exit(1)

    provision_tables()

    if SEED_DATA:
        seed_all()
    else:
        print("\n  Skipping data seed (SEED_DATA=false).")

    print("\n" + "=" * 60)
    print("  Done! Check your Catalyst Data Store console.")
    print("=" * 60)
    print("""
Next step — generate synthetic data (if you haven't yet):
  python data/generator/generate_synthetic_data.py

Then re-run with SEED_DATA=true to insert the rows.
""")


if __name__ == "__main__":
    main()
