/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as RiskScoresRouteImport } from './routes/risk-scores'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as AIChatbotRouteImport } from './routes/ai-chatbot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskScoresRoute = RiskScoresRouteImport.update({
  id: '/risk-scores',
  path: '/risk-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const AIChatbotRoute = AIChatbotRouteImport.update({
  id: '/ai-chatbot',
  path: '/ai-chatbot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/risk-scores': typeof RiskScoresRoute
  '/network': typeof NetworkRoute
  '/ai-chatbot': typeof AIChatbotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/risk-scores': typeof RiskScoresRoute
  '/network': typeof NetworkRoute
  '/ai-chatbot': typeof AIChatbotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/risk-scores': typeof RiskScoresRoute
  '/network': typeof NetworkRoute
  '/ai-chatbot': typeof AIChatbotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/overview' | '/risk-scores' | '/network' | '/ai-chatbot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/overview' | '/risk-scores' | '/network' | '/ai-chatbot'
  id: '__root__' | '/' | '/overview' | '/risk-scores' | '/network' | '/ai-chatbot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverviewRoute: typeof OverviewRoute
  RiskScoresRoute: typeof RiskScoresRoute
  NetworkRoute: typeof NetworkRoute
  AIChatbotRoute: typeof AIChatbotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-scores': {
      id: '/risk-scores'
      path: '/risk-scores'
      fullPath: '/risk-scores'
      preLoaderRoute: typeof RiskScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chatbot': {
      id: '/ai-chatbot'
      path: '/ai-chatbot'
      fullPath: '/ai-chatbot'
      preLoaderRoute: typeof AIChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverviewRoute: OverviewRoute,
  RiskScoresRoute: RiskScoresRoute,
  NetworkRoute: NetworkRoute,
  AIChatbotRoute: AIChatbotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
